### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by MADscientist314** [algo-cancer/CAMMiQ#1]
I am having trouble getting the install to recognize the CPLEX studio install.  I installed cplex from the bin and used the default install dir, as well as checked and changed permissions and ensureed it wasnt a permissions issue.  I even tried including the `/include/` subdirectory in the --cplex-dir.
Any advice?

` jochum00@aagaardlab1:sh install_CAMMiQ.sh --cplex-dir /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/`

...

`query.cpp:12:10: fatal error: ilcplex/ilocplex.h: No such file or directory
 #include <ilcplex/ilocplex.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:31: ../cammiq] Error 1`

`jochum00@aagaardlab1:ls /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/include/ilcplex/
annotation.xsd  cplexdistmipl.h  cplex.h        cplexremotel.h        cplexremotemasters.h  cplexremoteworker.h   cplexremoteworkerx.h  cplexx.h    ilocarray.h  iloCPXCALLBACKINFOenum.h              ilogoals.h      solution.xsd  vmc.xsd
cplexcheck.h    cplexdistmips.h  cplexl.h       cplexremotemaster.h   cplexremotemasterx.h  cplexremoteworkerl.h  cplexremotex.h        cpxconst.h  ilocplex.h   iloCPXCALLBACKSOLUTIONSTRATEGYenum.h  ilomodelasst.h  solution.xsl
cplexdistmip.h  cplexdistmipx.h  cplexremote.h  cplexremotemasterl.h  cplexremotes.h        cplexremoteworkers.h  cplexs.h              ilm.h       ilocplexi.h  iloextrmgr.h                          iloparam.h      vmc.dtd`

**Comment by tonyjhlam** [comment]
Also having the same issue.

**Comment by kyzhu** [comment]
Hi, can you try "install_CAMMiQ.sh --cplex-dir /opt/ibm/ILOG/CPLEX_Studio_Community129"? I think the directory should be your cplex studio.

**Comment by kyzhu** [comment]
> I am having trouble getting the install to recognize the CPLEX studio install. I installed cplex from the bin and used the default install dir, as well as checked and changed permissions and ensureed it wasnt a permissions issue. I even tried including the `/include/` subdirectory in the --cplex-dir.
> Any advice?
> 
> ` jochum00@aagaardlab1:sh install_CAMMiQ.sh --cplex-dir /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/`
> 
> ...
> 
> `query.cpp:12:10: fatal error: ilcplex/ilocplex.h: No such file or directory #include <ilcplex/ilocplex.h> ^~~~~~~~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:31: ../cammiq] Error 1`
> 
> `jochum00@aagaardlab1:ls /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/include/ilcplex/ annotation.xsd cplexdistmipl.h cplex.h cplexremotel.h cplexremotemasters.h cplexremoteworker.h cplexremoteworkerx.h cplexx.h ilocarray.h iloCPXCALLBACKINFOenum.h ilogoals.h solution.xsd vmc.xsd cplexcheck.h cplexdistmips.h cplexl.h cplexremotemaster.h cplexremotemasterx.h cplexremoteworkerl.h cplexremotex.h cpxconst.h ilocplex.h iloCPXCALLBACKSOLUTIONSTRATEGYenum.h ilomodelasst.h solution.xsl cplexdistmip.h cplexdistmipx.h cplexremote.h cplexremotemasterl.h cplexremotes.h cplexremoteworkers.h cplexs.h ilm.h ilocplexi.h iloextrmgr.h iloparam.h vmc.dtd`

**Comment by kyzhu** [comment]
> I am having trouble getting the install to recognize the CPLEX studio install. I installed cplex from the bin and used the default install dir, as well as checked and changed permissions and ensureed it wasnt a permissions issue. I even tried including the `/include/` subdirectory in the --cplex-dir.
> Any advice?
> 
> ` jochum00@aagaardlab1:sh install_CAMMiQ.sh --cplex-dir /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/`
> 
> ...
> 
> `query.cpp:12:10: fatal error: ilcplex/ilocplex.h: No such file or directory #include <ilcplex/ilocplex.h> ^~~~~~~~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:31: ../cammiq] Error 1`
> 
> `jochum00@aagaardlab1:ls /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/include/ilcplex/ annotation.xsd cplexdistmipl.h cplex.h cplexremotel.h cplexremotemasters.h cplexremoteworker.h cplexremoteworkerx.h cplexx.h ilocarray.h iloCPXCALLBACKINFOenum.h ilogoals.h solution.xsd vmc.xsd cplexcheck.h cplexdistmips.h cplexl.h cplexremotemaster.h cplexremotemasterx.h cplexremoteworkerl.h cplexremotex.h cpxconst.h ilocplex.h iloCPXCALLBACKSOLUTIONSTRATEGYenum.h ilomodelasst.h solution.xsl cplexdistmip.h cplexdistmipx.h cplexremote.h cplexremotemasterl.h cplexremotes.h cplexremoteworkers.h cplexs.h ilm.h ilocplexi.h iloextrmgr.h iloparam.h vmc.dtd`

Please let me know whether the above comment resolves the problem.

Thanks a lot!

**Comment by kyzhu** [comment]
Updated the installation script. Tested on multiple Linux servers.
